# Generated by Django 6.0.6 on 2026-06-19 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('photoPath', models.ImageField(upload_to='photos/')),
                ('aviaryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.aviary', verbose_name='Номер Загона')),
            ],
        ),
    ]
